---
tap_install:
  values:
    buildservice:
      kp_default_repository: gcr.io/dp-app-dash-ply-ab/tbs
      kp_default_repository_secret:
        name: tbs-repo-push
        namespace: tap-install
    ceip_policy_disclosed: true
    cnrs:
      domain_name: 127.0.0.1.nip.io
    contour:
      envoy:
        service:
          type: LoadBalancer
      infrastructure_provider: vsphere
    excluded_packages:
    - learningcenter.tanzu.vmware.com
    - workshops.learningcenter.tanzu.vmware.com
    local_source_proxy:
      push_secret:
        create_export: true
        name: lsp-registry-credentials
        namespace: tap-install
      repository: gcr.io/dp-app-dash-ply-ab/lsp
    ootb_supply_chain_basic:
      gitops:
        ssh_secret: ""
      registry:
        repository: dp-app-dash-ply-ab/tbs
        server: gcr.io
    profile: iterate
    shared:
      ingress_domain: 127.0.0.1.nip.io
      ingress_issuer: ''
      kubernetes_distribution: ''
    supply_chain: basic
    tap_telemetry:
      installed_for_vmware_internal_use: 'true'